### PR TITLE
fix not awaited coroutine

### PR DESCRIPTION
**Pull request by tadly**
I'm not a 100% on this.
I'm actually having an issue with a component of another project (home-assistant) and found a warning in the log.

If this is actually a bug, it would be nice to have a new release sometime soon as it currently breaks the kodi media player component of homeassistant :)

### CODE REVIEW

**Comment by emlove** [comment]
Ah, I see. It looks like aiohttp 3 changed this from a function to a coroutine: https://docs.aiohttp.org/en/stable/changes.html#id8

**Comment by tadly** [comment]
Didn't expect an answer that soon ':D
I see you're already digging deeper. If there's anything I can help with, let me know :)

**Comment by emlove** [comment]
Hah, just happened to be online!

The change is good, just need to tweak the CI and deps to reflect the new minimum version. I'll get a new version released shortly.

**Comment by bernimoses** [comment]
FYI from aiohttp 3 changelog:
> Drop Python 3.4 and Python 3.5.0, 3.5.1, 3.5.2. Minimal supported Python versions are 3.5.3 and 3.6.0. yield from is gone, use async/await syntax.

**Pull request merged**
